site_name: Am I Learning Enough
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Resources:
    - Assembly: resources/assembly/asm.md
    - Cheatsheets: 
      - RISC-V 32-bit: resources/cheatsheets/riscv-32bit.md
    - Computer Architecture: resources/computerArchitecture/compArch.md
    - Scientists:
      - Kepler: resources/scientists/Keplers.md
    - Database:
      - Reading Papers: resources/database/research-papers.md
    - Cybersecurity:
      - CybSec: resources/cybersecurity/cybsec.md
    - Linux:
      - BPF Tools: resources/linux/bpftrace-eBPF-tools.md
      - Networking Tools: resources/linux/linux-networking-tools.md
      - Performance Tools: resources/linux/linux-perf-benchmark-tools.md
      - Performance Tuning: resources/linux/linux-performace-tuning-tools.md
      - Static Performance Tools: resources/linux/linux-static-performace-tools.md
      - Sed: resources/linux/sed.md
      - File System Hierarchy: resources/linux/unix-file-system-hierarachy.md
    - Machine Learning:
      - Under The Hood of Neural Networks: resources/ml/underTheHoodOfNeuralNetwork.md
    - Operating System:
      - Overview: resources/operatingSystem/Readme.md
      - Cache Memory: resources/operatingSystem/cacheMemory.md
      - Concept of Virtual Memory: resources/operatingSystem/conceptOfVirtualMem.md
      - Contiguous Memory Allocation: resources/operatingSystem/contiguousMemAlloc.md
      - CPU: resources/operatingSystem/cpu.md
      - Disk Fragmentation: resources/operatingSystem/diskFragmentation.md
      - Disk Structure: resources/operatingSystem/diskStructure.md
      - Distributed Systems: resources/operatingSystem/distributedSystems.md
      - Embedded OS: resources/operatingSystem/embeddedOS.md
      - File System Implementation: resources/operatingSystem/fileSystemImplementation.md
      - File System: resources/operatingSystem/fileSystem.md
      - Free Space Management: resources/operatingSystem/freeSpaceManagement.md
      - Input/Output Hardware: resources/operatingSystem/inputOutputHardware.md
      - Input/Output Software: resources/operatingSystem/inputOutputSoftware.md
      - Input/Output Techniques: resources/operatingSystem/inputOutputTechniques.md
      - Interrupts: resources/operatingSystem/interrupts.md
      - Kernel I/O Subsystem: resources/operatingSystem/kernelIOSubsystem.md
      - Layered Architecture: resources/operatingSystem/layeredArchitecture.md
      - Logical vs Physical Addresses: resources/operatingSystem/logicalVsPhysicalAddresses.md
      - Memory Mapped Files: resources/operatingSystem/memoryMappedFiles.md
      - Microkernel: resources/operatingSystem/microKernel.md
      - Monolithic Kernel: resources/operatingSystem/monolithicKernel.md
      - OS Design and Implementation: resources/operatingSystem/osDesignAndImplementation.md
      - Page Replacement Algorithms: resources/operatingSystem/pageReplacementAlgo.md
      - Paging: resources/operatingSystem/paging.md
      - Process and Threads: resources/operatingSystem/processAndThreads.md
      - Process Management Structures: resources/operatingSystem/processManagementStructures.md
      - Process Scheduling: resources/operatingSystem/processScheduling.md
      - Protection in OS: resources/operatingSystem/protectionInOS.md
      - Real-time OS: resources/operatingSystem/realTimeOS.md
      - Security Mechanism: resources/operatingSystem/securityMechanism.md
      - Security Threats and Attacks: resources/operatingSystem/securityThreatsAndAttacks.md
      - Segmentation: resources/operatingSystem/segmentation.md
      - Software Layers: resources/operatingSystem/softwareLayers.md
      - System Calls: resources/operatingSystem/systemCalls.md
      - Thrashing: resources/operatingSystem/thrashing.md
      - Von Neumann Architecture: resources/operatingSystem/vonNeumannArchitecture.md
    - Programming:
      - C: resources/programming/c.md
      - Emacs: resources/programming/emacs.md
    - Reverse Engineering:
      - Reverse Engineering and Binary Exploitation: resources/reverse-engineering/re-and-be.md
    - University Courses: 
      - Courses: resources/univCourses/univ.md
  - Roadmaps:
    - DSA: 
      - Overview: roadmap/dsa/dsa.md
      - DSA using C: roadmap/dsa/dsaUsingC.md
    - Machine Learning:
      - Neural Networks with C: roadmap/ml/neuralNetsWithC.md
    - OS Development:
      - With C: roadmap/os-dev/knowC.md
      - Without C: roadmap/os-dev/noC.md
    - Reverse Engineering: 
      - RE: roadmap/reverse-engineering/reverse-engineering.md

extra_javascript:
  - https://gc.zgo.at/count.js

extra_css:
  - stylesheets/goatcounter.css

extra:
  goatcounter:
    site: learningresource
    domain: learningresource.goatcounter.com
